open-policy-agent/contrib

api_authz/Makefile
build/make-all.sh

The make-all.sh script wasn't using set -e so errors were not causing the build to fail.

Fail build on any error

---

api_authz/README.md
pam_authz/README.md

Link to tutorials from README and include just the basics in the README

Move README tutorials to opa repo

---

api_authz/docker/echo_server.py

- b64decode returns python bytes which needs to be convert to string
before splitting

Fixing User Split Issues

---

pam_authz/Makefile
pam_authz/README.md
pam_authz/pam/display.c

Add flag `--force-recreate` to `docker-compose up` command so that trial containers don't persist. 
Also fixed a couple of typos.

Edit /pam_authz Makefile target `up`.

---

kafka_authorizer/Makefile

Forgot to include push target in original PR. All subdirs with
publishable artifacts should include a push target for convenience.

Add push target to kafka_authorizer

---

.gitignore
.travis.yml
build/install-opa.sh
data_filter_example/Makefile
data_filter_example/data_filter_example/opa.py
data_filter_example/data_filter_example/sql.py
data_filter_example/tests/test_opa.py

These commits are somewhat independent but I made them all in a row and figured there was no reason to split up PRs at this point. Each commit is fairly self explanatory. With these changes:
- callers can control how SQL predicates are rendered as strings
- the filter integration tests use `opa eval` instead of requiring an OPA API endpoint
- the tests should executed as part of the CI
- the CI has been updated to install the latest stable version of OPA into the `$PATH`
I'm guessing something will break. Let's see.

Add quote option to data filter example and improve CI

---

decision_logger_plugin_example/main.go

We modified the decision logger interface to allow implementations to
return errors.

Update decision logger example

---

build/install-opa.sh

GitHub's rate limiting is brutal for Travis since so many jobs share
the same IP address. Add retry/backoff to the download script.

Add retry/backoff to OPA download

---

api_authz/docker/docker-compose-token.yaml
api_authz/docker/docker-compose.yaml

Update the docker-compose files for `api_authz` example to fix #49

Update api_authz example to use OPA v0.10.5

---

pam_authz/docker/docker-compose.yaml
pam_authz/docker/pam-builder.dockerfile

Increases the version of the golang container used to build the module,
and increases the version of opa used in the docker-compose example
Signed-off-by: Andy Curtis <arcurtis@gmail.com>

Update pam_authz build

---

data_filter_example/data_filter_example/opa.py

The docs in the data_filter_example use lowercase for the HTTP method,
which is internally consistent, but inconsistent with the example.rego
used. Instead, use uppercase in the doc example to match.
Fixes #53
Signed-off-by: Alejandro Wainzinger <aikawarazuni@gmail.com>

Update data_filter_example docs to match example.rego.

---

.gitignore
wasm/cloudflare-worker/README.md
wasm/cloudflare-worker/example.rego
wasm/cloudflare-worker/index.js
wasm/cloudflare-worker/metadata_wasm.json
wasm/cloudflare-worker/package-lock.json
wasm/cloudflare-worker/package.json
wasm/cloudflare-worker/webpack.config.js

The application itself isn’t super exciting but shows a couple of cool
things. First off this is a working example of using the new
`@open-policy-agent/opa-wasm` npm module. It also shows Cloudflare
workers (CDN edge compute) that can apply Rego policies on requests.

Add example javascript wasm app (Cloudflare worker)

---

.travis.yml

This unblocks @urvil38 who is working on a OPA-IPTables integration
for GSoC 2019.

travis: Update to Go 1.11 from Go 1.10

---

api_authz/docker/docker-compose-token.yaml
api_authz/docker/docker-compose.yaml
api_authz/docker/policy/api_authz.rego
api_authz/docker/policy/api_authz_token.rego

This PR addresses #75 by fixing the `io.jwt.decode` syntax, as well as making other more cosmetic changes to the contributed example to sync it with the [tutorial](https://www.openpolicyagent.org/docs/latest/http-api-authorization) so that it's easier to follow along with the tutorial while using the contrib example.

Update api_authz contrib example to match current tutorial

---

decision_logger_plugin_example/.gitignore
decision_logger_plugin_example/README.md
decision_logger_plugin_example/main.go

In v0.14.0 we deprecated Go plugin support. This just updates the
example to show how to build from source.

Update decision logger plugin example

---

pam_authz/pam/Makefile

Ubuntu 18.04.2 LTS was unable to build a working plugin without the reordering.

Switch library order for newer Ubuntu.

---

pam_authz/pam/README.md
pam_authz/pam/flag.c
pam_authz/pam/flag.h
pam_authz/pam/http.c

This change allows contacting OPA via unix socket rather then over tcp. This can be used to secure OPA when used with the pam module.

Add pam_authz support for unix socket to opa.

---

kafka_authorizer/src/main/java/com/lbg/kafka/opa/OpaAuthorizer.java

This PR is to set up default parameters for kafka opa authorizer to avoid null pointer exceptions.
It also provides an option to use authentication token when talking to opa.

Allow kafka plugin to talk to authenticated opa server

---

envoy_iptables/Makefile
envoy_iptables/proxy_init.sh

- introduce an optional parameter to redirect all outbound packets to a different envoy listener port
- the outbound parameter defaults to inbound port when not specified

allow configuring outbound and inbound ports for envoy iptables rules

---

kafka_authorizer/pom.xml

Th Kafka Authorizer currently doesn't compile under Java 11 because of too old version of the Lombok dependency. This PR bumps the Lombok version to fix this. It still works with Java 8 and Java 8 as source and target versions, just makes it compile under Java 11 as well.

Make the Kafka Authorizer compilable under Java 11

---

kafka_authorizer/README.md

This PR adds the `opa.authorizer.token` option to the README.md file to make it easy to find without looking into the source codes.

Add authentication token to the README.md file

---

data_filter_elasticsearch/README.md

The installation steps to elastic search isn't working. So updated to the latest installation home page of ES.
fixes: #110 
Signed-off-by: Vineeth Pothulapati <vineethpothulapati@outlook.com>
cc @ashutosh-narkar

Fix elastic search installation URL

---

envoy_iptables/Makefile
envoy_iptables/README.md
envoy_iptables/proxy_init.sh

This updates the script to have a new parameter `-w` which accepts a
comma separated list of ports. Inbound traffic for these ports will
be configured to bypass the envoy proxy by `RETURN`ing early in the
`ENVOY_IN_REDIRECT` chain.
By default there are no open ports, thus the change is backwards
compatible.
Any users of the OPA+Envoy integration that want to use a health check
on a separate port (using `--diagnostic-addr`) will likely need to
update their deployments to use this new flag.
Signed-off-by: Patrick East <east.patrick@gmail.com>

envoy_iptables: Add port whitelist to bypass envoy

---

data_filter_azure/data_filter_azure/opa.py
data_filter_azure/data_filter_azure/sql.py
data_filter_example/data_filter_example/opa.py
data_filter_example/data_filter_example/server.py
data_filter_example/data_filter_example/sql.py

> One of the changes from Python 2 to Python 3 was PEP 3105, which changes the convention of print to be a called function, which requires the use of parenthesis. These have not yet been changed across the whole codebase.
Changes according to the comment

Resolve #42. Changing the print statement to function

---

data_filter_azure/requirements.txt

The azure-storage package has been deprecated so the build needs to
pin to the original version from requirements.txt.

data_filter_azure: Fix build to pin azure-storage dependency

---

kafka_authorizer/scripts/build.sh

Was printing thousands of lines in the build output.
With --quiet will only print errors.

Add --quiet flag to kafka build

---

k8s_authorization/Makefile
k8s_authorization/README.md
k8s_authorization/api-server/authz-webhook.yaml
k8s_authorization/config/kind-conf.yaml
k8s_authorization/kubernetes/resources.yaml
k8s_authorization/kustomization.yaml
k8s_authorization/policy/policy.rego
k8s_authorization/setup.sh
k8s_authorization/test.sh

Add example project demonstrating kubernetes webhook authorization using OPA.
Since most of the complexities with kubernetes authorization webhooks are not
about the actual authorization policies but rather about how to properly
configure kubernetes, this project uses kind to launch a local cluster for
testing.
To be followed up with a blog post going into the details of the configuration
and the caveats one needs to consider for this type of setup.

Kubernetes authorization webhook

---

README.md

Semi-related: I think we should replace the "This a list of integrations that are not currently part of the contrib repository" list with a link to https://www.openpolicyagent.org/docs/latest/ecosystem/

Update index of projects

---

README.md

Removed from listing, status:
- Kong: Already on ecosystem page.
- PHP: Already on ecosystem page.
- Helm: POC project not maintained for 3 years, did not build at all.
- Habitat: No longer maintained by @srenatus. Can add later if maintained.
- Flask: Reached out to maintainer and asked about adding to ecosystem page.
- ANTLR: PR up for adding to ecosystem page.

External links -> ecosystem

---

gatekeeper_mtail_violations_exporter/Dockerfile
gatekeeper_mtail_violations_exporter/Makefile
gatekeeper_mtail_violations_exporter/README.md
gatekeeper_mtail_violations_exporter/gatekeeper.mtail
gatekeeper_mtail_violations_exporter/kustomization.yaml
gatekeeper_mtail_violations_exporter/mtail_service.yaml
gatekeeper_mtail_violations_exporter/mtail_sidecar_patch.yaml

At T-Mobile we use this sidecar to scrape the gatekeeper audit-loop logs from the audit container and then expose them on a prometheus metrics endpoint, we'd like to contribute it back for anyone who is looking to use this or a similar pattern for getting audited violation details out of Gatekeeper.
Contained in this PR is:
A Dockerfile for building the mtail image
Mtail code largely written by @ghsbhatia
a kustomization.yaml and patches to deploy gatekeeper with the sidecar.

Violation Metrics Export Sidecar for Gatekeeper

---

spring_authz/.gitignore
spring_authz/pom.xml
spring_authz/src/main/java/org/openpolicyagent/voter/OPADataRequest.java
spring_authz/src/main/java/org/openpolicyagent/voter/OPADataResponse.java
spring_authz/src/main/java/org/openpolicyagent/voter/OPAVoter.java

While at it:
- Bump Java to version 11.
- Bump all other dependencies to their latest versions.
- Fix Maven warnings.
- Avoid possible NPE.

Bump insecure Spring dependencies

---

kong_api_authz/src/kong/plugins/opa/access.lua

When no token is provided with the request, the execution fail the attempt to index the field 'payload' (a nil value).
In case the subject from the JWT token is not be defined or there's no token, 'anonymous' will be used instead.
Fixes open-policy-agent/contrib#146

kong_api_authz: Fix error when no JWT token is provided

---

open_api/openapi.yaml

I was going off the REST API docs on openpolicyagent.org [here](https://www.openpolicyagent.org/docs/v0.36.1/rest-api/#create-or-overwrite-a-document) and confirmed that this API seems to take a request body
Example request from that link:
> ```
> PUT /v1/data/us-west/servers HTTP/1.1
> Content-Type: application/json
> If-None-Match: *
>
> {}
> ```
I confirmed that [this part of the server implementation looks at the request body](https://github.com/open-policy-agent/opa/blob/829086a2e04da57d0b4e76008fbe6ac825c7929e/server/server.go#L1675)
and then verified it on a local OPA server (version `0.34.2`)
```
curl -XPUT -H'content-type: application/json' localhost:8181/v1/data/foo -d '{"foo": true}'
curl localhost:8181/v1/data/foo
```
outputs
```
{"result":{"foo":true}}
```
I specifically …

Include request body as an input to PUT /v1/data/{path}

---

.github/workflows/build.yaml
build/make-all.sh
envoy_iptables/Makefile

build cross-platform images for envoy_iptables

---

build/make-all.sh

Because the build for gatekeeper_mtail_violations_exporter is broken,
disable it for the time being.
Potential fix: https://github.com/open-policy-agent/contrib/pull/166#issuecomment-1087686778
Signed-off-by: Charles Daniels <charles@styra.com>

build: disable gatekeeper_mtail_violations_exporter

---

build/make-all.sh

I am able to build pam_opa locally, however in GitHub Actions, the build
is failing due to the error:
ERROR: The certificate of 'www.digip.org' is not trusted.
Signed-off-by: Charles Daniels <charles@styra.com>

build: disable pam_opa

---

simplecov/README.md
simplecov/example/policy.rego
simplecov/example/policy_test.rego
simplecov/simplecov.rego

Add SimpleCov coverage format conversion example

---

kong_api_authz/README.md
kong_api_authz/src/kong/plugins/opa/access.lua
kong_api_authz/src/kong/plugins/opa/schema.lua

Added new config option whereby a list of request header names can be specified.
The matching request headers and their values will become part of the document passed to OPA.
This is for scenarios where header information plays a part in policy decision making.

Kong OPA Plugin: include selected headers in OPA document

---

spring_authz/README.md

Minor updates to the spring_authz README to make it easier to use gradle to build the example, and also to view the data going into and out of opa during the authorization process

Add gradle configuration hints and opa debugging flag to existing instructions

---

.github/dependabot.yml

We've been getting a few save-state and set-output warnings, those should go away with updating some actions.

dependabot: update actions

---

kong_api_authz/README.md
kong_api_authz/integration/docker-compose.test.yml
kong_api_authz/integration/testdata/kong-test.yml
kong_api_authz/integration/testdata/postman/docker.postman_environment.json
kong_api_authz/integration/testdata/postman/kong-plugin-opa.integration_tests.postman_collection.json
kong_api_authz/integration/testdata/postman/wait-for-services.sh
kong_api_authz/integration/toxiproxy.json
kong_api_authz/spec/__mocks__/resty/http.lua
kong_api_authz/spec/kong/plugins/opa/access_spec.lua
kong_api_authz/src/kong/plugins/opa/access.lua
kong_api_authz/src/kong/plugins/opa/schema.lua

With this enhancement, Kong administrators have the _option_ to set timeouts on OPA policy evaluation calls.  This will enable API Gateway operators to guard against unruly OPA policies creeping into API transactions and blowing up request times.

Support for configurable connect/send/read timeout on OPA HTTP connection in kong_api_authz module.

---

README.md
sonarcloud/README.md
sonarcloud/example/policy.rego
sonarcloud/example/policy_test.rego
sonarcloud/opa_coverage_to_sonarcloud.py

This PR is based on https://github.com/open-policy-agent/contrib/tree/main/cobertura to generate generic test data report for SonarCloud / SonarQube (https://docs.sonarcloud.io/enriching/test-coverage/generic-test-data/). More information can be found in README file.

feat: Added script to generate SonarCloud test report

---

open_api/openapi.yaml

Backported from https://github.com/StyraInc/enterprise-opa/pull/64
Secondary concerns ftw!

Add `exclude-plugin` parameter to `/health` endpoint

---

opa-iptables/go.mod
opa-iptables/go.sum
opa-iptables/main.go
opa-iptables/pkg/controller/controller.go
opa-iptables/pkg/controller/types.go
opa-iptables/pkg/opa/opa.go

- Added functionality to pass a bearer token during OPA connections.
- Registered the self-signed CA used to sign the OPA server certificate as a trusted CA, enabling HTTPS connections.

feat: Add bearer token support and trust self-signed CA for HTTPS in OPA

---

cobertura/opa_coverage_to_cobertura.py

When a rego file is not covered, the script fails with an exception due to the OPA coverage format.
I added a small logic to handle this case gracefully

fix(cobertura): handle files without coverage gracefully
