open-policy-agent/contrib

pam_authz/pam/pam_authz.go
=> Fix indentity file config option, drop group config option

.travis.yml, Makefile, api_authz/Makefile, build/make-all.sh, pam_authz/Makefile
=> Add top-level makefile to build all integrations

README.md
/cc @timothyhinrichs @arcurtis
=> Flesh out top-level README

README.md, linkerd_authz/.gitignore, linkerd_authz/README.md, linkerd_authz/build.sbt, linkerd_authz/project/plugins.sbt, linkerd_authz/sbt, linkerd_authz/src/main/resources/META-INF/services/io.buoyant.linkerd.IdentifierInitializer, linkerd_authz/src/main/scala/org/openpolicyagent/linkerd/identifier.scala
This is copied from the original repository at github.com/tsandall/opa-linkerd-authz.
=> Add microservice authorization example with Linkerd

README.md, image_enforcer/.gitignore, image_enforcer/Dockerfile.run, image_enforcer/Makefile, image_enforcer/README.md, image_enforcer/clair/clair.go, image_enforcer/data/clair/clair.json, image_enforcer/data/docker/docker.json, image_enforcer/docker/docker.go, image_enforcer/main.go, image_enforcer/manifests/deployment.yaml, image_enforcer/manifests/service.yaml, image_enforcer/opa/opa.go, image_enforcer/policies/default.rego, image_enforcer/policies/mock/input.rego, image_enforcer/policies/scan.rego
=> Add Kubernetes image enforcement example

api_authz/README.md, pam_authz/README.md
the link is broken, just an update
=> Update step-by-step doc link

pam_authz/README.md, pam_authz/pam/README.md, pam_authz/pam/authz.h, pam_authz/pam/display.c, pam_authz/pam/log.c, pam_authz/pam/sysinfo.c, pam_authz/pam/sysinfo.h
- Add missing snippets to READMEs, and fix some bad names.
- Add/fix some comments in the code.
=> Make PAM integration docs more complete.

.travis.yml
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Update go version in travis config

data_filter_elasticsearch/README.md, data_filter_elasticsearch/internal/es/es.go
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Ignore unmapped path for Nested Query

data_filter_elasticsearch/data.json, data_filter_elasticsearch/example.rego
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Update policy for multi-condition data

README.md
=> Reference Flask-OPA as external integration project

data_filter_example/README.md
=> Add note about experimental status of SQL translation

build/install-opa.sh
=> Fix OPA install script to follow redirects

iptables/postman-collection/README.md, iptables/postman-collection/collection/OPA.postman_collection.json
- iptables folder is a place for OPA iptables integration, on which I am working on as a part of GSOC student.
- I also added postman collection for learning and testing OPA REST API.
=> iptables OPA Integration

iptables/postman-collection/collection/OPA.postman_collection.json
- added APIs related to query and policies in postman collection. current collection contains following API
1. Data API
2. Query API
3. Policy API
=> added query and policy releted API in postman collection

opa-iptables/main.go, opa-iptables/pkg/controller/controller.go, opa-iptables/pkg/controller/handlers.go, opa-iptables/pkg/controller/types.go, opa-iptables/pkg/opa/opa.go
- Added server which handles webhook request
- OPA client to query data document
=> Added Controller and Functionality related to query data document

envoy_iptables/Dockerfile, envoy_iptables/Makefile, envoy_iptables/README.md, envoy_iptables/proxy_init.sh
Script to install iptables rules to redirect traffic through the Envoy proxy sidecar.
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add package to redirect traffic to Envoy

k8s_node_selector/.devcontainer/Dockerfile, k8s_node_selector/.devcontainer/devcontainer.json, k8s_node_selector/Makefile, k8s_node_selector/README.MD, k8s_node_selector/authz.rego, k8s_node_selector/data_input.rego, k8s_node_selector/integration/deploy/.gitignore, k8s_node_selector/integration/deploy/admission-controller.yaml, k8s_node_selector/integration/deploy/deploy.sh, k8s_node_selector/integration/test/int_test.py, k8s_node_selector/main.rego, k8s_node_selector/requirements.txt, k8s_node_selector/test_node_selector.rego, k8s_node_selector/testdata/pod.yaml, k8s_node_selector/testdata/sample-request.json
This example aims to be as simple and readable as possible, for more advanced work the README directs to the existing library helpers.
Todo:
=> Simple mutating example with K8s

junit/README.md, junit/opa_test_to_junit.py
Needed this for integrating OPA tests in some of our existing projects and figured that it might save somebody else a few hours if this was included here.
Signed-off-by: Anders Eknert <anders.eknert@bisnode.com>
=> OPA JSON test output -> JUnit report conversion

kafka_authorizer/src/main/java/com/lbg/kafka/opa/OpaAuthorizer.java
The Kafka Authorizer code is using Guava cache to cache the results from OPA to avoid calling the OPA service everytime the `authorize` method is called (which would be for example with every produced message or with every `poll` - so very often). 
However, the way it is written right now, the cache does not seem to be used. The problem is, that the cache is created when the `OpaAuthorizer` object initializes - so even before the `cofnigure` method is called by Kafka for the first time and the defaults are set all as 0 (default value for int / long). So nothing is really cached.
It also seems that configuration valus are never removed from the local `configs` map. So use cannot for example remove any option to return to the default.
This PR does the following:
* Adds the constructor which …
=> Fix the use of the Guava cache in Kafka Authorizer

pam_opa/pam/README.md
Signed-off-by: Andy Curtis <arcurtis@gmail.com>
=> Add warning to pam_opa install instructions

k8s_api_client/README.md, k8s_api_client/kind-config.yaml, k8s_api_client/kustomization.yaml, k8s_api_client/policy/api_client.rego, k8s_api_client/resources/deployment.yaml, k8s_api_client/resources/ingress.yaml, k8s_api_client/resources/rbac.yaml, k8s_api_client/resources/secret.yaml, k8s_api_client/resources/service.yaml, k8s_api_client/resources/serviceaccount.yaml, k8s_api_client/setup.sh, k8s_api_client/test.sh
Add example library for querying the kubernetes API from inside the cluster.
Signed-off-by: Anders Eknert <anders@styra.com>
=> Kubernetes API client for Rego

junit/opa_test_to_junit.py
=> Support skipped tests

opa-iptables/README.md
This edit is for people like me who copy and paste instructions without thinking
=> fixed typo in opa-iptables readme

.github/workflows/build.yaml, open_api/management.yaml, open_api/openapi.yaml
Also removed some redundant comments found while doing that.
=> Rename master -> main

kafka_authorizer/README.md
..and point to the new one + docs.
=> Deprecate Kafka plugin

api_authz/docker/docker-compose.yaml
Note: recreated PR based on #176 for signing. 
Signed-off-by: Mikhail Kozorovitskiy <mikhail@thecrazyrussian.com>
=> updating opa version and reverting to 0.2 example api docker image.

envoy_iptables/proxy_init.sh
As discussed at issue https://github.com/open-policy-agent/opa/issues/5233, I have updated to fix this issue. For more info, I have checked every `iptables` chain/rule before create/append a new one.
=> Init-proxy has restart and crash loopback.

kong_api_authz/Dockerfile, kong_api_authz/spec/kong/plugins/opa/access_spec.lua
=> Fix unit and integration tests for Kong OPA Plugin.

open_api/openapi.yaml
=> OpenAPI: use application/yaml over application/x-yaml

kong_api_authz/src/kong/plugins/opa/access.lua
The Kong OPA plugin currently only supports boolean response format (result: true/false) but the Kong OPA specification defines two valid formats: boolean and object.
This adds support for the object format where OPA can return:
```
{
"result": {
"allow": true/false,
"status": 403,
"message": "Custom error message"
}
}
```
The object format allows policies to provide custom HTTP status codes and error messages for denied requests, enabling more granular authorization responses.
- Add type checking to handle both boolean and object result formats
- Respect custom status codes and messages from object format
- Maintain backward compatibility with existing boolean format
- Add appropriate error handling for invalid result types
Enables richer authorization responses while maintaining …
=> feat: add support for OPA object response format
